# Docker Compose file for a Baikal server with MariaDB 5
# Based on issue https://github.com/ckulka/baikal-docker/issues/10

version: "2"
services:
  baikal:
    image: ckulka/baikal:nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - config:/var/www/baikal/config
      - data:/var/www/baikal/Specific

  db:
    image: mariadb:10
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: adalovelace
      MYSQL_DATABASE: baikal
      MYSQL_USER: baikal
      MYSQL_PASSWORD: ilovecookies
    volumes:
      - db:/var/lib/mysql

volumes:
  config:
  data:
  db:
