# See
# - https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions
# - https://docs.github.com/en/actions/learn-github-actions/contexts
# - https://github.com/docker/build-push-action/blob/master/docs/advanced/multi-platform.md
name: Build experimental images

on:
  # Rebuild every week on Sunday at 8:00 UTC
  # schedule:
  #   - cron: 0 8 * * 0

  # Allow manually triggered rebuilds
  workflow_dispatch:

  # Build on push to master
  push:
    branches:
      - master
    paths:
      - .github/workflows/build-experimental.yaml
      - "*.dockerfile"
      - files/**

jobs:
  test:
    name: ${{ matrix.dockerfile }}
    uses: ./.github/workflows/test-job.yaml
    with:
      dockerfile: ${{ matrix.dockerfile }}
    strategy:
      fail-fast: true
      matrix:
        dockerfile:
          - apache
          # - apache-php8.2
          - nginx
          # - nginx-php8.2

  apache:
    name: Apache
    needs: test
    uses: ./.github/workflows/build-job.yaml
    with:
      dockerfile: apache.dockerfile
      baikal-version: experimental
      tags: |
        ckulka/baikal:experimental-apache
        ckulka/baikal:experimental
    secrets: inherit

  # apache_php82:
  #   name: Apache (PHP 8.2)
  #   needs: test
  #   uses: ./.github/workflows/build-job.yaml
  #   with:
  #     dockerfile: apache-php8.2.dockerfile
  #     baikal-version: experimental
  #     tags: |
  #       ckulka/baikal:experimental-apache-php8.2
  #       ckulka/baikal:experimental-php8.2
  #   secrets: inherit

  nginx:
    name: Nginx
    needs: test
    uses: ./.github/workflows/build-job.yaml
    with:
      dockerfile: nginx.dockerfile
      baikal-version: experimental
      tags: ckulka/baikal:experimental-nginx
    secrets: inherit

  # nginx_php82:
  #   name: Nginx (PHP 8.2)
  #   needs: test
  #   uses: ./.github/workflows/build-job.yaml
  #   with:
  #     dockerfile: nginx-php8.2.dockerfile
  #     baikal-version: experimental
  #     tags: ckulka/baikal:experimental-nginx-php8.2
  #   secrets: inherit
