# See
# - https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions
# - https://docs.github.com/en/actions/learn-github-actions/contexts
# - https://github.com/docker/build-push-action/blob/master/docs/advanced/multi-platform.md
name: Publish Baikal Experimental Image

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build experimental image
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - file: apache.dockerfile
            tags: |
              ckulka/baikal:experimental-apache
              ckulka/baikal:experimental
          - file: nginx.dockerfile
            tags: ckulka/baikal:experimental-nginx

    steps:
      - uses: actions/checkout@v4
        with:
          show-progress: false

      # See https://github.com/docker/setup-qemu-action
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      # See https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # See https://github.com/docker/login-action
      # - name: Login to DockerHub
      #   uses: docker/login-action@v3
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_PASSWORD }}

      # Build Apache httpd images
      - name: Build ${{ matrix.file }}
        uses: docker/build-push-action@v5
        with:
          file: ${{ matrix.file }}
          # platforms: linux/amd64,linux/arm/v7,linux/arm64/v8,linux/386
          # push: false
          tags: ${{ matrix.tags }}
