# See
# - https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions
# - https://docs.github.com/en/actions/learn-github-actions/contexts
# - https://github.com/docker/build-push-action/blob/master/docs/advanced/multi-platform.md
name: Publish Baikal Experimental Image

on:
  push:
    branches:
      - master

jobs:
  mailslurper:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build MailSlurper
        uses: docker/build-push-action@v5
        with:
          context: https://github.com/mailslurper/mailslurper.git#release-1.15.0
          tags: mailslurper/mailslurper
          outputs: type=docker,dest=/tmp/mailslurper.tar

      - name: Upload MailSlurper image artifact
        uses: actions/upload-artifact@v4
        with:
          name: mailslurper
          path: /tmp/mailslurper.tar

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: apache
            file: apache.dockerfile
            tags: |
              ckulka/baikal:experimental-apache
              ckulka/baikal:experimental
          - name: nginx
            file: nginx.dockerfile
            tags: ckulka/baikal:experimental-nginx

    steps:
      - uses: actions/checkout@v4
        with:
          show-progress: false

      # See https://github.com/docker/setup-qemu-action
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      # See https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # See https://github.com/docker/login-action
      # - name: Login to DockerHub
      #   uses: docker/login-action@v3
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_PASSWORD }}

      # Build Apache httpd images
      - name: Build ${{ matrix.name }}
        id: build
        uses: docker/build-push-action@v5
        with:
          file: ${{ matrix.file }}
          platforms: linux/amd64,linux/arm/v7,linux/arm64/v8,linux/386
          outputs: type=docker,dest=/tmp/${{ matrix.name }}.tar
          tags: ${{ matrix.tags }}

      - name: Upload Baikal image artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.name }}
          path: /tmp/${{ matrix.name }}.tar

  test:
    runs-on: ubuntu-latest
    needs:
      - build
    strategy:
      matrix:
        name: [apache, nginx]
    steps:
      - name: Download Baikal image artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ matrix.name }}
          path: /tmp

      - name: Load Docker image
        run: docker load --input /tmp/${{ matrix.name }}.tar

      - uses: actions/checkout@v4
        with:
          show-progress: false

      # Install Cypress dependencies
      - uses: actions/setup-node@v4
        with:
          node-version-file: package.json
          cache: npm

      - name: Install Cypress dependencies
        run: npm ci

      - name: Start Baikal container
        run: docker run --rm --detach --publish 80:80 ckulka/baikal:experimental-${{ matrix.name }}

      - name: Run Cypress tests
        run: npm run test

  test-mail:
    runs-on: ubuntu-latest
    needs:
      - mailslurper
      - build
    strategy:
      matrix:
        name: [apache, nginx]
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: /tmp
          merge-multiple: true

      - name: Load Docker images
        run: |
          docker load --input /tmp/mailslurper.tar
          docker load --input /tmp/${{ matrix.name }}.tar

      - uses: actions/checkout@v4
        with:
          show-progress: false

      # Install Cypress dependencies
      - uses: actions/setup-node@v4
        with:
          node-version-file: package.json
          cache: npm

      - name: Install Cypress dependencies
        run: npm ci

      - name: Run MailSlurper
        run: docker run --name mailslurper --rm --detach --publish 8085:8085 -v ${{ github.workspace }}/cypress/fixtures/mailslurper-config.json:/config.json:ro mailslurper/mailslurper

      - name: Start Baikal container with MSMTP configuration
        env:
          MSMTPRC: |
            account default
            host    mailslurper
            port    2500
            from    baikal@example.com
        run: |
          docker run --name ${{ matrix.name }} --rm --detach --publish 80:80 --env MSMTPRC="$MSMTPRC" --link mailslurper ckulka/baikal:experimental-${{ matrix.name }}
          docker cp ${{ github.workspace }}/cypress/fixtures/mail-test.php ${{ matrix.name }}:/var/www/baikal/html/

      - name: Run Cypress tests incl. MSMTP
        run: CYPRESS_MSMTP_ENABLED=TRUE npm run test
